uzh-network-ninjas/ase-social-network

- docker-compose.yml
- ms-authenticate/app/main.py
- ms-authenticate/requirements.txt
- ms-user/app/main.py
- ms-user/requirements.txt
added the necessary docker compose structure for the user database and some provisional code that accesses it
> initial database setup for authentication and user

- docker-compose.yml
cannot start docker compose without this hotfix as the db depends on the volume
> fixing the missing line for the user db volume

- ms-frontend/index.html
- ms-frontend/src/App.vue
- ms-frontend/src/assets/main.css
- ms-frontend/src/icons/MagnifyingGlassIcon.vue
- ms-frontend/src/main.ts
- ms-frontend/src/presets/button/index.ts
- ms-frontend/src/presets/checkbox/index.ts
- ms-frontend/src/presets/floatlabel/index.ts
- ms-frontend/src/presets/global.ts
- ms-frontend/src/presets/iconfield/index.ts
- ms-frontend/src/presets/index.ts
- ms-frontend/src/presets/inputtext/index.ts
- ms-frontend/src/presets/ripple/index.ts
- ms-frontend/src/views/HomeView.vue
- ms-frontend/tailwind.config.js
> Added PT presets for Button, TextField and Checkbox

- ms-frontend/package-lock.json
- ms-frontend/package.json
- ms-frontend/src/components/TopNav.vue
- ms-frontend/src/icons/ArrowLeftStartOnRectangle.vue
- ms-frontend/src/icons/BaseIcon.vue
- ms-frontend/src/services/authService.ts
- ms-frontend/src/services/axios.ts
- ms-frontend/src/services/userService.ts
- ms-frontend/src/stores/auth.ts
- ms-frontend/src/types/User.ts
- ms-frontend/src/views/HomeView.vue
- ms-frontend/src/views/SignInView.vue
- Fixed type errors in HomeView topNavActions
- Added missing ArrowLeftStartOnRectangle Icon (log-out)
- Fixed return type of login functions
- Stored jwt token
- Called user endpoint with userId provided by jwt
- Fixed incomplete registration process, by calling login function
- Added functionality to perform logout
> Suggested changes for Merge Request 29-ur02-login

- ms-authenticate/app/AuthenticateController.py
- ms-authenticate/app/AuthenticateRepository.py
- ms-authenticate/app/AuthenticateService.py
- ms-authenticate/app/models/UpdateUserPassword.py
- ms-authenticate/app/models/UserLogin.py
- ms-authenticate/app/models/UserLoginIn.py
- ms-authenticate/app/models/UserRegister.py
> Possibility to update password

- ms-user/app/UserController.py
- ms-user/app/UserService.py
- ms-user/app/models/User.py
adjusted user models and added controller & service logic to add/update the profile picture; closes #92
> profile picture logic

- ms-authenticate/app/AuthenticateController.py
- ms-authenticate/app/AuthenticateRepository.py
- ms-authenticate/app/AuthenticateService.py
- ms-authenticate/app/models/UserRegister.py
> add login on register

- down.sh
- ms-authenticate/app/AuthenticateController.py
- ms-authenticate/app/models/UserRegister.py
- ms-user/app/UserController.py
- ms-user/app/UserRepository.py
- ms-user/app/UserService.py
- ms-user/app/models/User.py
closes #96 closes #12 closes #13
> 96 following other users

- docker-compose.yml
- ms-review/app/ReviewController.py
- ms-review/app/ReviewRepository.py
- ms-review/app/ReviewService.py
- ms-review/app/models/Review.py
- support/localstack/localstack-setup.sh
> create and get reviews

- ms-authenticate/app/AuthenticateController.py
- ms-user/app/UserController.py
- ms-user/app/UserService.py
- ms-user/app/models/UserListOut.py
> 114 models following follower

- ms-review/app/ReviewController.py
- ms-review/app/ReviewRepository.py
- ms-review/app/ReviewService.py
- ms-review/app/models/Location.py
- ms-review/app/models/ReviewCreate.py
- ms-review/app/models/ReviewOut.py
- ms-user/app/UserService.py
> 100 queries for reviews

- ms-frontend/src/icons/ArrowDown.vue
- ms-frontend/src/icons/ArrowLeftStartOnRectangle.vue
- ms-frontend/src/icons/ArrowUp.vue
- ms-frontend/src/icons/BaseIcon.vue
- ms-frontend/src/icons/ExclamationCircleIcon.vue
- ms-frontend/src/icons/EyeIcon.vue
- ms-frontend/src/icons/EyeSlashIcon.vue
- ms-frontend/src/icons/MagnifyingGlassIcon.vue
- ms-frontend/src/icons/SparklesIcon.vue
- ms-frontend/src/main.ts
- ms-frontend/src/presets/index.ts
- ms-frontend/src/presets/togglebutton/index.ts
- ms-frontend/src/views/TestView.vue
> Added size modifier to Icons
> Created preset for ToggleButton Component.

- ms-user/app/UserController.py
- ms-user/app/UserService.py
- ms-user/app/models/DietaryCriteria.py
- ms-user/app/models/Preferences.py
- ms-user/app/models/Restrictions.py
closes #101; added checks if dietary criteria (preferences and restrictions) are valid and an endpoint to get all possibilities
> dietary criteria

- ms-user/app/UserRepository.py
- ms-user/app/UserService.py
closes #126; added checks to avoid duplicate usernames and emails
> unique userdata

- ms-authenticate/app/AuthenticateRepository.py
- ms-authenticate/app/models/UserOut.py
- ms-authenticate/app/models/UserRegister.py
- ms-review/app/ReviewController.py
- ms-review/app/ReviewRepository.py
- ms-review/app/ReviewService.py
- ms-review/app/models/ReviewCreate.py
- ms-user/app/UserController.py
- ms-user/app/UserRepository.py
- ms-user/app/UserService.py
closes #128; following a user raising excption and various datetime bugs
> various bugs

- ms-frontend/src/components/SignedInTopNav.vue
- ms-frontend/src/views/Settings/AccountSettingsView.vue
Fixed missing check if passwords are identical in AccountSettingsView update password to enable update button. Formatting
> Fixed wrong error code check in AccountSettingsView update password.

- ms-review/app/ReviewController.py
- ms-review/app/ReviewRepository.py
- ms-review/app/ReviewService.py
- ms-review/app/models/Location.py
- ms-review/app/models/LocationIDs.py
- ms-review/app/models/ReviewListFilteredOut.py
closes #148; adjusting filtering for reviews and added location-type
> Fix filter for reviews

- README.md
- ms-authenticate/tests/test_controller.py
- run_tests.sh
> 147 testing ms authenticate

- ms-frontend/src/components/CreateReviewModal.vue
- ms-frontend/src/components/PlaceItem.vue
- ms-frontend/src/components/PlaceReview.vue
- ms-frontend/src/components/PlaceView.vue
- ms-frontend/src/components/StarRating.vue
- ms-frontend/src/i18n/de.json
- ms-frontend/src/i18n/en.json
- ms-frontend/src/icons/UploadIcon.vue
- ms-frontend/src/presets/textarea/index.ts
- ms-frontend/src/services/reviewService.ts
- ms-frontend/src/types/Location.ts
- ms-frontend/src/utils/timeConverter.ts
- ms-frontend/src/views/MapView.vue
- ms-frontend/src/views/ProfileView.vue
> Added place search results displayed as a list

- ms-review/app/ReviewController.py
- ms-review/app/ReviewRepository.py
- ms-review/app/ReviewService.py
- ms-review/tests/test_controller.py
- ms-review/tests/test_service.py
> Improvements and refactoring

- ms-authenticate/app/AuthenticateController.py
- ms-authenticate/app/AuthenticateRepository.py
- ms-authenticate/app/AuthenticateService.py
- ms-review/app/ReviewController.py
> 174 ms authenticate cleansing

- ms-authenticate/app/AuthenticateController.py
- ms-authenticate/app/AuthenticateRepository.py
- ms-authenticate/app/AuthenticateService.py
- ms-review/app/ReviewController.py
- ms-review/app/ReviewService.py
- ms-review/tests/test_controller.py
- ms-review/tests/test_service.py
- ms-user/app/UserController.py
- ms-user/app/UserRepository.py
- ms-user/app/UserService.py
- ms-user/tests/test_controller.py
> 175 ms user cleansing
